clear;
fig = gcf;
axObjs = gca;
dataObjs = axObjs.Children;
x = dataObjs(1).XData;
y = dataObjs(1).YData;
zdata1 = dataObjs(1).ZData;
cdata1 = dataObjs(1).CData;
%a = gca;
%editfigure(z,c);

%function editfigure(zdata1, cdata1)
%CREATEFIGURE(zdata1, cdata1)
%  ZDATA1:  surface zdata
%  CDATA1:  surface cdata

%  Auto-generated by MATLAB on 06-Oct-2020 12:11:16

% Create figure
figure('InvertHardcopy','off','Color',[1 1 1],...
    'OuterPosition',[276 287 576 513]);
colormap(jet(64));

% Create axes
%axes1 = axes;
%hold(axes1,'on');
axes1=gca;
% Create surf
surf1 = surf(zdata1,cdata1,'FaceLighting','none','EdgeLighting','flat',...
    'FaceColor',[1 1 1],...
    'EdgeColor','interp');

% The following line demonstrates an alternative way to create a data tip.
% datatip(surf1,306,29,-0.038049641700402);
% Create datatip
%datatip(surf1,'DataIndex',10399);

% Create ylabel
ylabel('PSM (cells)');

% Create xlabel
xlabel('Time (steps)');

% Create title
%title('SFC d=1/6 su=1.5','FontName','Arial', 'FontSize', '28');
title('Raw ppERK','FontName','Arial', 'FontSize', '28');


%if behaves weird run this part separately

axes1=gca;
% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0 400]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0 35]);
% Uncomment the following line to preserve the Z-limits of the axes
zlim(axes1,[-1 40]);
view(90,90);
% Set the remaining axes properties
set(gca,'BoxStyle','full','FontName','Arial','FontSize',20,'LineWidth',...
    1.5,'XGrid','on','XTick',[0 70 140 210 280 350],'YGrid','on','YTick',...
    [0 5 10 15 20 25 30 35 40]);
% Create colorbar
colorbar(gca,'FontSize',16);
%end


